import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { memo, useEffect, useState } from "react";
import { getGun, useGun } from "../hooks/gun/useGun";
import { getGunItem, setGunItem, useGunItem } from "../hooks/gun/useGunItem";
import { withExportCache, withImportCache } from "../util/gunCache";

export const getStaticProps: GetStaticProps = async () => {
  const gun = getGun().get("guncmsblogthingRoot");
  setGunItem("alpha", 2);
  setGunItem("beta", 20);
  await getGunItem("alpha");
  await getGunItem("beta");

  const props = {
    props: withExportCache({}),
    revalidate: 30,
  };

  return props;
};

const Sub = () => {
  const { item: alpha } = useGunItem<number>("alpha");
  const { item: beta } = useGunItem<number>("beta");
  useGunItem<number>("beta");
  return (
    <div>
      <h3>Alpha</h3>
      <p>
        <span>{alpha}</span>
      </p>
      <h3>Beta</h3>
      <p>
        <span>{beta}</span>
      </p>
    </div>
  );
};

const BetaRenderMeasurer = memo(() => {
  console.log("Render beta");
  const { item: beta } = useGunItem<number>("beta");
  return (
    <div>
      <h3>Beta</h3>
      <p>
        <span>{beta}</span>
      </p>
    </div>
  );
});

BetaRenderMeasurer.displayName = "BetaRenderMeasurer";

const AlphaRenderMeasurer = memo(() => {
  console.log("Render alpha");
  const { item: alpha } = useGunItem<number>("alpha");
  return (
    <div>
      <h3>Alpha</h3>
      <p>
        <span>{alpha}</span>
      </p>
    </div>
  );
});

AlphaRenderMeasurer.displayName = "AlphaRenderMeasurer";

const Home: NextPage = () => {
  const [field, setField] = useState<string>("alpha");
  const { item } = useGunItem<number>(field);

  const gun = useGun().get("guncmsblogthingRoot");
  const actionOne = () => {
    setField((field) => (field === "alpha" ? "beta" : "alpha"));
  };

  const actionTwo = () => {
    const res = setGunItem(field, (item || 0) + 1);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <button onClick={actionOne}>action one</button>
        <button onClick={actionTwo}>action two</button>
        <h2>item</h2>
        <code>{JSON.stringify(item)}</code>
        <AlphaRenderMeasurer />
        <BetaRenderMeasurer />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default withImportCache(Home);
